// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.4
// source: uno.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 卡牌的结构体
type UnoCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId uint32 `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"` // 卡牌ID
	Color  uint32 `protobuf:"varint,2,opt,name=color,proto3" json:"color,omitempty"`                 // 1、2、3、4代表四种颜色，你爱用哪个用哪个，等价的。0代表黑牌
	Num    uint32 `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`                     // 0-9是数字牌 10代表“跳过”牌 11代表“反向”牌 12代表“+2牌” 13代表黑牌中的变色牌 14代表黑牌中的“+4”牌
}

func (x *UnoCard) Reset() {
	*x = UnoCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uno_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnoCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnoCard) ProtoMessage() {}

func (x *UnoCard) ProtoReflect() protoreflect.Message {
	mi := &file_uno_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnoCard.ProtoReflect.Descriptor instead.
func (*UnoCard) Descriptor() ([]byte, []int) {
	return file_uno_proto_rawDescGZIP(), []int{0}
}

func (x *UnoCard) GetCardId() uint32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *UnoCard) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *UnoCard) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// 通知客户端：初始化游戏
type InitToc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerNum uint32     `protobuf:"varint,1,opt,name=player_num,json=playerNum,proto3" json:"player_num,omitempty"` // 玩家总人数（包括你）
	Cards     []*UnoCard `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`                           // 你的初始手牌
}

func (x *InitToc) Reset() {
	*x = InitToc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uno_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitToc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitToc) ProtoMessage() {}

func (x *InitToc) ProtoReflect() protoreflect.Message {
	mi := &file_uno_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitToc.ProtoReflect.Descriptor instead.
func (*InitToc) Descriptor() ([]byte, []int) {
	return file_uno_proto_rawDescGZIP(), []int{1}
}

func (x *InitToc) GetPlayerNum() uint32 {
	if x != nil {
		return x.PlayerNum
	}
	return 0
}

func (x *InitToc) GetCards() []*UnoCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

// 通知客户端：其他玩家摸牌
type OtherAddHandCardToc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint32 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家ID 你的下家是1 下下家是2 以此类推
	Num      uint32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`                           // 增加的手牌数量
}

func (x *OtherAddHandCardToc) Reset() {
	*x = OtherAddHandCardToc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uno_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OtherAddHandCardToc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtherAddHandCardToc) ProtoMessage() {}

func (x *OtherAddHandCardToc) ProtoReflect() protoreflect.Message {
	mi := &file_uno_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtherAddHandCardToc.ProtoReflect.Descriptor instead.
func (*OtherAddHandCardToc) Descriptor() ([]byte, []int) {
	return file_uno_proto_rawDescGZIP(), []int{2}
}

func (x *OtherAddHandCardToc) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *OtherAddHandCardToc) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// 通知客户端：你摸牌
type DrawCardToc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card []*UnoCard `protobuf:"bytes,1,rep,name=card,proto3" json:"card,omitempty"`
}

func (x *DrawCardToc) Reset() {
	*x = DrawCardToc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uno_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrawCardToc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawCardToc) ProtoMessage() {}

func (x *DrawCardToc) ProtoReflect() protoreflect.Message {
	mi := &file_uno_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawCardToc.ProtoReflect.Descriptor instead.
func (*DrawCardToc) Descriptor() ([]byte, []int) {
	return file_uno_proto_rawDescGZIP(), []int{3}
}

func (x *DrawCardToc) GetCard() []*UnoCard {
	if x != nil {
		return x.Card
	}
	return nil
}

// 通知客户端：现在到谁的回合了
type NotifyTurnToc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint32 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家ID 你是0 你的下家是1 下下家是2 以此类推
	Dir      bool   `protobuf:"varint,2,opt,name=dir,proto3" json:"dir,omitempty"`                           // true-顺时针 false-逆时针
}

func (x *NotifyTurnToc) Reset() {
	*x = NotifyTurnToc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uno_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyTurnToc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyTurnToc) ProtoMessage() {}

func (x *NotifyTurnToc) ProtoReflect() protoreflect.Message {
	mi := &file_uno_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyTurnToc.ProtoReflect.Descriptor instead.
func (*NotifyTurnToc) Descriptor() ([]byte, []int) {
	return file_uno_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyTurnToc) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *NotifyTurnToc) GetDir() bool {
	if x != nil {
		return x.Dir
	}
	return false
}

// 通知客户端：牌堆剩余数量（如果变多了，说明洗牌了）
type SetDeckNumToc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num uint32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *SetDeckNumToc) Reset() {
	*x = SetDeckNumToc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uno_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDeckNumToc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeckNumToc) ProtoMessage() {}

func (x *SetDeckNumToc) ProtoReflect() protoreflect.Message {
	mi := &file_uno_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeckNumToc.ProtoReflect.Descriptor instead.
func (*SetDeckNumToc) Descriptor() ([]byte, []int) {
	return file_uno_proto_rawDescGZIP(), []int{5}
}

func (x *SetDeckNumToc) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// 出牌
type DiscardCardTos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId    uint32 `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`          // 出的牌的ID
	WantColor uint32 `protobuf:"varint,2,opt,name=want_color,json=wantColor,proto3" json:"want_color,omitempty"` // 出黑牌时，选择想要的颜色
}

func (x *DiscardCardTos) Reset() {
	*x = DiscardCardTos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uno_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscardCardTos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardCardTos) ProtoMessage() {}

func (x *DiscardCardTos) ProtoReflect() protoreflect.Message {
	mi := &file_uno_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardCardTos.ProtoReflect.Descriptor instead.
func (*DiscardCardTos) Descriptor() ([]byte, []int) {
	return file_uno_proto_rawDescGZIP(), []int{6}
}

func (x *DiscardCardTos) GetCardId() uint32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *DiscardCardTos) GetWantColor() uint32 {
	if x != nil {
		return x.WantColor
	}
	return 0
}

// 通知客户端：某玩家出牌（自己出牌后，服务端也会返回这个协议）
type DiscardCardToc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId  uint32   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家ID 你是0 你的下家是1 下下家是2 以此类推
	Card      *UnoCard `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
	WantColor uint32   `protobuf:"varint,3,opt,name=want_color,json=wantColor,proto3" json:"want_color,omitempty"` // 出黑牌时，选择想要的颜色
}

func (x *DiscardCardToc) Reset() {
	*x = DiscardCardToc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uno_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscardCardToc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardCardToc) ProtoMessage() {}

func (x *DiscardCardToc) ProtoReflect() protoreflect.Message {
	mi := &file_uno_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardCardToc.ProtoReflect.Descriptor instead.
func (*DiscardCardToc) Descriptor() ([]byte, []int) {
	return file_uno_proto_rawDescGZIP(), []int{7}
}

func (x *DiscardCardToc) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *DiscardCardToc) GetCard() *UnoCard {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *DiscardCardToc) GetWantColor() uint32 {
	if x != nil {
		return x.WantColor
	}
	return 0
}

// 通知客户端谁赢了
type NotifyWinToc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint32 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家ID 你是0 你的下家是1 下下家是2 以此类推
}

func (x *NotifyWinToc) Reset() {
	*x = NotifyWinToc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_uno_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyWinToc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyWinToc) ProtoMessage() {}

func (x *NotifyWinToc) ProtoReflect() protoreflect.Message {
	mi := &file_uno_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyWinToc.ProtoReflect.Descriptor instead.
func (*NotifyWinToc) Descriptor() ([]byte, []int) {
	return file_uno_proto_rawDescGZIP(), []int{8}
}

func (x *NotifyWinToc) GetPlayerId() uint32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

var File_uno_proto protoreflect.FileDescriptor

var file_uno_proto_rawDesc = []byte{
	0x0a, 0x09, 0x75, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x08, 0x75,
	0x6e, 0x6f, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x61, 0x72, 0x64, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x4a, 0x0a, 0x08, 0x69, 0x6e, 0x69, 0x74,
	0x5f, 0x74, 0x6f, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e,
	0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x4e, 0x75, 0x6d, 0x12, 0x1f, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x75, 0x6e, 0x6f, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x52, 0x05, 0x63,
	0x61, 0x72, 0x64, 0x73, 0x22, 0x48, 0x0a, 0x17, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x61, 0x64,
	0x64, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x6f, 0x63, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x2e,
	0x0a, 0x0d, 0x64, 0x72, 0x61, 0x77, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x6f, 0x63, 0x12,
	0x1d, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x75, 0x6e, 0x6f, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x40,
	0x0a, 0x0f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x74, 0x6f,
	0x63, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x64, 0x69, 0x72,
	0x22, 0x24, 0x0a, 0x10, 0x73, 0x65, 0x74, 0x5f, 0x64, 0x65, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d,
	0x5f, 0x74, 0x6f, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x4a, 0x0a, 0x10, 0x64, 0x69, 0x73, 0x63, 0x61, 0x72,
	0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x6f, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61,
	0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x61, 0x72,
	0x64, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x61, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x77, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x22, 0x6d, 0x0a, 0x10, 0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x63, 0x61,
	0x72, 0x64, 0x5f, 0x74, 0x6f, 0x63, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x75, 0x6e, 0x6f, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61,
	0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x61, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x77, 0x61, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x6f,
	0x72, 0x22, 0x2d, 0x0a, 0x0e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x77, 0x69, 0x6e, 0x5f,
	0x74, 0x6f, 0x63, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_uno_proto_rawDescOnce sync.Once
	file_uno_proto_rawDescData = file_uno_proto_rawDesc
)

func file_uno_proto_rawDescGZIP() []byte {
	file_uno_proto_rawDescOnce.Do(func() {
		file_uno_proto_rawDescData = protoimpl.X.CompressGZIP(file_uno_proto_rawDescData)
	})
	return file_uno_proto_rawDescData
}

var file_uno_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_uno_proto_goTypes = []interface{}{
	(*UnoCard)(nil),             // 0: uno_card
	(*InitToc)(nil),             // 1: init_toc
	(*OtherAddHandCardToc)(nil), // 2: other_add_hand_card_toc
	(*DrawCardToc)(nil),         // 3: draw_card_toc
	(*NotifyTurnToc)(nil),       // 4: notify_turn_toc
	(*SetDeckNumToc)(nil),       // 5: set_deck_num_toc
	(*DiscardCardTos)(nil),      // 6: discard_card_tos
	(*DiscardCardToc)(nil),      // 7: discard_card_toc
	(*NotifyWinToc)(nil),        // 8: notify_win_toc
}
var file_uno_proto_depIdxs = []int32{
	0, // 0: init_toc.cards:type_name -> uno_card
	0, // 1: draw_card_toc.card:type_name -> uno_card
	0, // 2: discard_card_toc.card:type_name -> uno_card
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_uno_proto_init() }
func file_uno_proto_init() {
	if File_uno_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_uno_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnoCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uno_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitToc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uno_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OtherAddHandCardToc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uno_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DrawCardToc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uno_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyTurnToc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uno_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDeckNumToc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uno_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscardCardTos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uno_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscardCardToc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_uno_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyWinToc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_uno_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_uno_proto_goTypes,
		DependencyIndexes: file_uno_proto_depIdxs,
		MessageInfos:      file_uno_proto_msgTypes,
	}.Build()
	File_uno_proto = out.File
	file_uno_proto_rawDesc = nil
	file_uno_proto_goTypes = nil
	file_uno_proto_depIdxs = nil
}
